/*
 * interface for: vette generated by elmer
 */

#define elNEWID -1

char* getTestString( );
int VetteData_create(char* data_file, int returnObjId );
void VetteData_load_data(int objId );
int VetteData_get_year(int objId );
float VetteData_get_dimension(int objId, char* dim );
int VetteData_get_options(int objId, int returnObjId );
int VetteData_get_option(int objId, char* opt_code, int returnObjId );
void VetteOption_set_code(int objId, char* opt_code );
void VetteOption_set_desc(int objId, char* description );
void VetteOption_set_quantity(int objId, int quan );
char* VetteOption_get_code(int objId );
char* VetteOption_get_desc(int objId );
int VetteOption_get_quantity(int objId );
void delete_obj( int objId );
